const assets = {
            accessories: {
                earings: './assets/alpaca/accessories/earings.png',
                flower: './assets/alpaca/accessories/flower.png',
                glasses: './assets/alpaca/accessories/glasses.png',
                headphone: './assets/alpaca/accessories/headphone.png',
                none: '',
            },
            backgrounds: {
                blue50: './assets/alpaca/backgrounds/blue50.png',
                blue60: './assets/alpaca/backgrounds/blue60.png',
                blue70: './assets/alpaca/backgrounds/blue70.png',
                darkblue30: './assets/alpaca/backgrounds/darkblue30.png',
                darkblue50: './assets/alpaca/backgrounds/darkblue50.png',
                darkblue70: './assets/alpaca/backgrounds/darkblue70.png',
                green50: './assets/alpaca/backgrounds/green50.png',
                green60: './assets/alpaca/backgrounds/green60.png',
                green70: './assets/alpaca/backgrounds/green70.png',
                grey40: './assets/alpaca/backgrounds/grey40.png',
                grey70: './assets/alpaca/backgrounds/grey70.png',
                grey80: './assets/alpaca/backgrounds/grey80.png',
                red50: './assets/alpaca/backgrounds/red50.png',
                red60: './assets/alpaca/backgrounds/red60.png',
                red70: './assets/alpaca/backgrounds/red70.png',
                yellow50: './assets/alpaca/backgrounds/yellow50.png',
                yellow60: './assets/alpaca/backgrounds/yellow60.png',
                yellow70: './assets/alpaca/backgrounds/yellow70.png',
            },
            ears: {
                default: './assets/alpaca/ears/default.png',
                backward: './assets/alpaca/ears/tilt-backward.png',
                forward: './assets/alpaca/ears/tilt-forward.png',
            },
            eyes: {
                angry: './assets/alpaca/eyes/angry.png',
                default: './assets/alpaca/eyes/default.png',
                naughty: './assets/alpaca/eyes/naughty.png',
                panda: './assets/alpaca/eyes/panda.png',
                smart: './assets/alpaca/eyes/smart.png',
                star: './assets/alpaca/eyes/star.png',
            },
            hair: {
                bang: './assets/alpaca/hair/bang.png',
                curls: './assets/alpaca/hair/curls.png',
                default: './assets/alpaca/hair/default.png',
                elegant: './assets/alpaca/hair/elegant.png',
                fancy: './assets/alpaca/hair/fancy.png',
                quiff: './assets/alpaca/hair/quiff.png',
                short: './assets/alpaca/hair/short.png',
            },
            leg: {
                tea: './assets/alpaca/leg/bubble-tea.png',
                cookie: './assets/alpaca/leg/cookie.png',
                default: './assets/alpaca/leg/default.png',
                console: './assets/alpaca/leg/game-console.png',
                backward: './assets/alpaca/leg/tilt-backward.png',
                forward: './assets/alpaca/leg/tilt-forward.png',
            },
            mouth: {
                astonished: './assets/alpaca/mouth/astonished.png',
                default: './assets/alpaca/mouth/default.png',
                eating: './assets/alpaca/mouth/eating.png',
                laugh: './assets/alpaca/mouth/laugh.png',
                tongue: './assets/alpaca/mouth/tongue.png',
            },
            neck: {
                backward: './assets/alpaca/neck/bend-backward.png',
                forward: './assets/alpaca/neck/bend-forward.png',
                default: './assets/alpaca/neck/default.png',
                thick: './assets/alpaca/neck/thick.png',
            },
            nose: {
                default: './assets/alpaca/nose.png'
            }
        }